### ISSUE TITLE
Some syntax changes coming down in 0.9.0

### ISSUE THREAD

**Issue by max-sixty** [PRQL/tree-sitter-prql#13]
Hi @matthias-Q !

Just to flag a couple of big changes coming down in [0.9.0](https://github.com/PRQL/prql/issues/2689). 

I'm happy to help with things if needed. I don't think they're _complicated_ changes — e.g. the tuple syntax is a straight swap, even though it's pervasive.

**Comment by matthias-Q** [comment]
Totally missed this one. I will take a look in the next days. Sorry for the silence @max-sixty

**Comment by max-sixty** [comment]
No prob! Thanks1

**Comment by matthias-Q** [comment]
@max-sixty is there a changelog or something? It is quite hard to find out what will be changed in 0.9.0

**Comment by max-sixty** [comment]
Yes! All the breaking changes should be labeled. 

I just put a PR to make the working a bit better: https://github.com/PRQL/prql/pull/3007

Let me know anything at all I can do to help...

**Comment by matthias-Q** [comment]
Thanks, a short example of the new function declaration and arrays would be nice. 
I just added modules following https://github.com/PRQL/prql/blob/58c391a5b4011c6841f0d67711adf82a696927e6/web/book/src/internals/modules.md

**Comment by max-sixty** [comment]
Great re modules!

The biggest change is the array / struct change.

Then [regex](https://github.com/PRQL/prql/blob/main/web/book/src/language-features/regex.md) & [functions](https://github.com/PRQL/prql/blob/main/web/book/src/queries/functions.md) are the only other significant ones.

Thanks!
